INSERT INTO tblroles (rol) VALUES
('usuario'),
('administrador');

INSERT INTO tblcategorias (nombre_categoria) VALUES
('Música'),
('Arte'),
('Deporte'),
('Académico');

INSERT INTO tbltarifas_evento (tarifa_evento) VALUES
('Gratis'),
('Pago');

INSERT INTO tblcomunas_medellin(nombre_comuna) VALUES
('Comuna 1: Popular'),
('Comuna 2: Santa Cruz'),
('Comuna 3: Manrique'),
('Comuna 4: Aranjuez'),
('Comuna 5: Castilla'),
('Comuna 6: Doce de Octubre'),
('Comuna 7: Robledo'),
('Comuna 8: Villa Hermosa'),
('Comuna 9: Buenos Aires'),
('Comuna 10: La Candelaria'),
('Comuna 11: Laureles - Estadio'),
('Comuna 12: La América'),
('Comuna 13: San Javier'),
('Comuna 14: El Poblado'),
('Comuna 15: Guayabal'),
('Comuna 16: Belén');

INSERT INTO tblbarrios_medellin(nombre_barrio, id_comuna) VALUES
-- Comuna 1: Popular
('Santo Domingo Savio No.1', 1),
('Santo Domingo Savio No.2', 1),
('Popular', 1),
('Granizal', 1),
('Moscu No.2', 1),
('Villa Guadalupe', 1),
('San Pablo', 1),
('El Compromiso', 1),
('Aldea Pablo VI', 1),
('La Esperanza No.2', 1),
('La Avanzada', 1),
('Carpinelo', 1),

-- Comuna 2: Santa Cruz
('La Isla', 2),
('El Playón de Los Comuneros', 2),
('Pablo VI', 2),
('La Frontera', 2),
('La Francia', 2),
('Andalucía', 2),
('Villa del Socorro', 2),
('Villa Niza', 2),
('Moscú No.1', 2),
('Santa Cruz', 2),
('La Rosa', 2),

-- Comuna 3: Manrique
('La Salle', 3),
('Las Granjas', 3),
('Campo Valdés No.2', 3),
('Santa Inés', 3),
('El Raizal', 3),
('El Pomar', 3),
('Manrique Central No.2', 3),
('Manrique Oriental', 3),
('Versalles No.1', 3),
('Versalles No.2', 3),
('La Cruz', 3),
('Oriente', 3),
('María Cano Carambolas', 3),
('San José de la Cima No.1', 3),
('San José de la Cima No.2', 3),

-- Comuna 4: Aranjuez
('Berlín', 4),
('San Isidro', 4),
('Palermo', 4),
('Bermejal Los Álamos', 4),
('Moravia', 4),
('Sevilla', 4),
('San Pedro', 4),
('Manrique Central No.1', 4),
('Campo Valdés No.1', 4),
('Las Esmeraldas', 4),
('La Piñuela', 4),
('Aranjuez', 4),
('Brasilia', 4),
('Miranda', 4),

-- Comuna 5: Castilla
('Toscana', 5),
('Las Brisas', 5),
('Florencia', 5),
('Tejelo', 5),
('Boyacá', 5),
('Héctor Abad Gómez', 5),
('Belalcázar', 5),
('Girardot', 5),
('Tricentenario', 5),
('Castilla', 5),
('Francisco Antonio Zea', 5),
('Alfonso López', 5),
('Caribe', 5),
('Progreso', 5),

-- Comuna 6: Doce de Octubre
('Santander', 6),
('Doce de Octubre No.1', 6),
('Doce de Octubre No.2', 6),
('Pedregal', 6),
('La Esperanza', 6),
('San Martín de Porres', 6),
('Kennedy', 6),
('Picacho', 6),
('Picachito', 6),
('Mirador del Doce', 6),
('Progreso No.2', 6),
('El Triunfo', 6),

-- Comuna 7: Robledo
('Cerro El Volador', 7),
('San Germán', 7),
('Facultad de Minas U.Nal', 7),
('La Pilarica', 7),
('Bosques de San Pablo', 7),
('Altamira', 7),
('Córdoba', 7),
('López de Mesa', 7),
('El Diamante', 7),
('Aures No.2', 7),
('Aures No.1', 7),
('Bello Horizonte', 7),
('Villa Flora', 7),
('Palenque', 7),
('Robledo', 7),
('Cucaracho', 7),
('Fuente Clara', 7),
('Santa Margarita', 7),
('Olaya Herrera', 7),
('Pajarito', 7),
('Monteclaro', 7),
('Nueva Villa de La Iguana', 7),

-- Comuna 8: Villa Hermosa
('Enciso', 8),
('El Pinal', 8),
('Villatina', 8),
('La Mansión', 8),
('Batallón Girardot', 8),
('Villa Hermosa', 8),
('La Ladera', 8),
('San Antonio', 8),
('Los Mangos', 8),
('Las Estancias', 8),
('La Sierra', 8),
('La Esperanza No.1', 8),

-- Comuna 9: Buenos Aires
('Juan Pablo II', 9),
('Barrios de Jesús', 9),
('Bomboná No.2', 9),
('Los Cerros El Vergel', 9),
('Alejandro Echavarría', 9),
('Barrio Caicedo', 9),
('Buenos Aires', 9),
('Miraflores', 9),
('Cataluña', 9),
('La Milagrosa', 9),
('Gerona', 9),
('El Salvador', 9),
('Loreto', 9),
('Asomadera No.1', 9),
('Asomadera No.2', 9),
('Asomadera No.3', 9),
('Ocho de Marzo', 9),

-- Comuna 10: La Candelaria
('La Candelaria', 10),

-- Comuna 11: Laureles - Estadio
('Carlos E. Restrepo', 11),
('Suramericana', 11),
('Naranjal', 11),
('San Joaquín', 11),
('Los Conquistadores', 11),
('Bolivariana', 11),
('Laureles', 11),
('Las Acacias', 11),
('La Castellana', 11),
('Lorena', 11),
('El Velódromo', 11),
('Estadio', 11),
('Los Colores', 11),
('Cuarta Brigada', 11),
('Florida Nueva', 11),

-- Comuna 12: La América
('Ferrini', 12),
('Calasanz', 12),
('Los Pinos', 12),
('La América', 12),
('La Floresta', 12),
('Santa Lucía', 12),
('El Danubio', 12),
('Campo Alegre', 12),
('Santa Mónica', 12),
('Barrio Cristóbal', 12),
('Simón Bolívar', 12),
('Santa Teresita', 12),
('Calasanz Parte Alta', 12),

-- Comuna 13: San Javier
('El Pesebre', 13),
('Blanquizal', 13),
('Santa Rosa de Lima', 13),
('Los Alcázares', 13),
('Metropolitano', 13),
('La Pradera', 13),
('Juan XIII – La Quiebra', 13),
('San Javier No.2', 13),
('San Javier No.1', 13),
('Veinte de Julio', 13),
('Belencito', 13),
('Betania', 13),
('El Corazón', 13),
('Las Independencias', 13),
('Nuevos Conquistadores', 13),
('El Salado', 13),
('Eduardo Santos', 13),
('Antonio Nariño', 13),
('El Socorro', 13),

-- Comuna 14: El Poblado
('Barrio Colombia', 14),
('Villa Carlota', 14),
('Castropol', 14),
('Lalinde', 14),
('Las Lomas No.1', 14),
('Las Lomas No.2', 14),
('Altos del Poblado', 14),
('El Tesoro', 14),
('Los Naranjos', 14),
('Los Balsos No.1', 14),
('Los Balsos No.2', 14),
('San Lucas', 14),
('El Diamante No.2', 14),
('El Castillo', 14),
('Alejandría', 14),
('La Florida', 14),
('El Poblado', 14),
('Manila', 14),
('Astorga', 14),
('Patio Bonito', 14),
('La Aguacatala', 14),
('Santa María de Los Ángeles', 14),

-- Comuna 15: Guayabal
('Tenche', 15),
('Trinidad', 15),
('Santa Fé', 15),
('Parque Juan Pablo II', 15),
('Campo Amor', 15),
('Noel', 15),
('Cristo Rey', 15),
('Guayabal', 15),

-- Comuna 16: Belén
('Fátima', 16),
('Rosales', 16),
('Belén', 16),
('Granada', 16),
('San Bernardo', 16),
('Las Playas', 16),
('Diego Echevarría', 16),
('La Mota', 16),
('Altavista', 16),
('Los Alpes', 16),
('La Palma', 16),
('El Rodeo', 16),
('La Hondonada', 16),
('La Loma de Los Bernal', 16),
('La Gloria', 16),
('El Nogal', 16),
('El Rincón', 16),
('Zafra', 16),
('Las Violetas', 16);










---------------------------------------------------------------------------
